[env]
TERM = "st-256color"

[window]
opacity = 0.8

[font]
normal = { family = "monospace", style = "Regular" }
size = 9

[colors.normal]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"


[colors.primary]
background = "#313131"
foreground = "#ebdbb2"

[cursor]
style = "Block"

[mouse]
hide_when_typing = false

# ADD OR MODIFY THIS SECTION
[terminal]
shell = { program = "zsh", args = ["-l"] }

[keyboard]
bindings = [
  { key = "V", mods = "Alt", action = "Paste" },
  { key = "C", mods = "Alt", action = "Copy" },
  { key = "Insert", mods = "Shift", action = "PasteSelection" },
  { key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Shift", action = "ScrollPageDown" },
  { key = "PageUp", mods = "Alt", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Alt", action = "ScrollPageDown" },
  { key = "K", mods = "Alt", action = "ScrollLineUp" },
  { key = "J", mods = "Alt", action = "ScrollLineDown" },
  { key = "ArrowUp", mods = "Alt", action = "ScrollLineUp" },
  { key = "ArrowDown", mods = "Alt", action = "ScrollLineDown" },
  { key = "U", mods = "Alt", action = "ScrollPageUp" },
  { key = "D", mods = "Alt", action = "ScrollPageDown" },

  # Font size control
  { key = "ArrowUp", mods = "Control|Alt", action = "IncreaseFontSize" },
  { key = "ArrowDown", mods = "Control|Alt", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Control|Alt", action = "ResetFontSize" }
]
